import { AuditLog } from './audit.ts';
import { MCPClient } from './mcp.ts';
import { streamLLM } from './llm.ts';

export class AgentRuntime {
  private maxSteps = 5;
  private maxRetries = 2;
  private audit: AuditLog;
  private mcp: MCPClient;
  private llmUrl: string;

  constructor(
    audit: AuditLog,
    mcp: MCPClient,
    llmUrl: string
  ) {
    this.audit = audit;
    this.mcp = mcp;
    this.llmUrl = llmUrl;
  }

  private promptBuilder(history: string, user: string): string {
    return `
You are a deterministic agent.

Rules:
- If using tools → ONLY JSON
- Else → final answer

Tools:
- test {val}
- add {a, b}

Conversation:
${history}

User: ${user}
Assistant:
`;
  }

  private parseTool(text: string): any {
    try {
      const jsonStart = text.indexOf('{');
      if (jsonStart === -1) return null;
      const json = text.slice(jsonStart);
      return JSON.parse(json);
    } catch {
      return null;
    }
  }

  private validateToolCall(obj: any): boolean {
    return !!(obj.tool && obj.args);
  }

  async run(userInput: string): Promise<string> {
    let history = '';
    let step = 0;

    while (step < this.maxSteps) {
      const prompt = this.promptBuilder(history, userInput);
      const raw = await streamLLM(this.llmUrl, prompt);

      this.audit.log(step, 'llm_raw', raw);

      const toolCall = this.parseTool(raw);

      // FINAL ANSWER
      if (!toolCall) {
        return raw;
      }

      // VALIDATION + RETRY
      let valid = this.validateToolCall(toolCall);
      let retries = 0;

      while (!valid && retries < this.maxRetries) {
        retries++;
        this.audit.log(step, 'retry', { original: toolCall, attempt: retries });

        const retryPrompt = `
Fix this JSON tool call (must be ONLY JSON):
${JSON.stringify(toolCall)}
`;

        const retryRaw = await streamLLM(this.llmUrl, retryPrompt);
        const retryParsed = this.parseTool(retryRaw);

        if (retryParsed && this.validateToolCall(retryParsed)) {
          Object.assign(toolCall, retryParsed);
          valid = true;
        }
      }

      if (!valid) {
        throw new Error('Invalid tool call generated by LLM');
      }

      // EXECUTE TOOL
      const result = await this.mcp.call(toolCall.tool, toolCall.args);
      this.audit.log(step, 'tool_result', result);

      // APPEND TO HISTORY
      history += `
Assistant (tool call): ${JSON.stringify(toolCall)}
Tool result: ${JSON.stringify(result.result)}
`;

      step++;
    }

    return 'Maximum steps reached.';
  }
}
