import { AuditLog } from './audit.ts';
import { MCPClient } from './mcp.ts';
import { streamLLM } from './llm.ts';
import { z } from 'zod';

export type ToolSchema = {
  name: string;
  schema: z.ZodObject<any>;
};

export class AgentRuntime {
  private maxSteps = 5;
  private maxRetries = 2;
  private audit: AuditLog;
  private mcp: MCPClient;
  private llmUrl: string;
  private tools: Map<string, ToolSchema> = new Map();

  constructor(
    audit: AuditLog,
    mcp: MCPClient,
    llmUrl: string
  ) {
    this.audit = audit;
    this.mcp = mcp;
    this.llmUrl = llmUrl;
  }

  registerTool(name: string, schema: z.ZodType<any>) {
    this.tools.set(name, { name, schema: schema as any });
  }

  private promptBuilder(history: string, user: string): string {
    return `
You are a deterministic agent.

Rules:
- If using tools → ONLY JSON
- Else → final answer

Tools:
- test {val}
- add {a, b}

Conversation:
${history}

User: ${user}
Assistant:
`;
  }

  private parseTool(text: string): any {
    try {
      const jsonStart = text.indexOf('{');
      if (jsonStart === -1) return null;
      const json = text.slice(jsonStart);
      return JSON.parse(json);
    } catch {
      return null;
    }
  }

  private validateToolCall(obj: any): { valid: boolean; error?: string } {
    if (!obj.tool || !obj.args) {
      return { valid: false, error: 'Missing "tool" or "args" field.' };
    }

    const tool = this.tools.get(obj.tool);
    if (!tool) {
      return { valid: false, error: `Tool "${obj.tool}" not found.` };
    }

    const result = (tool.schema as any).safeParse(obj.args);
    if (!result.success) {
      const errors = result.error.errors || result.error.issues || [];
      const errorMsg = errors.map((e: any) => `${e.path.join('.')}: ${e.message}`).join(', ');
      return {
        valid: false,
        error: `Invalid arguments for tool "${obj.tool}": ${errorMsg}`
      };
    }

    return { valid: true };
  }

  async run(userInput: string): Promise<string> {
    let history = '';
    let step = 0;

    while (step < this.maxSteps) {
      const prompt = this.promptBuilder(history, userInput);
      const raw = await streamLLM(this.llmUrl, prompt);

      this.audit.log(step, 'llm_raw', raw);

      const toolCall = this.parseTool(raw);

      // FINAL ANSWER
      if (!toolCall) {
        return raw;
      }

      // VALIDATION + RETRY
      let { valid, error } = this.validateToolCall(toolCall);
      let retries = 0;

      while (!valid && retries < this.maxRetries) {
        retries++;
        this.audit.log(step, 'retry', { original: toolCall, error, attempt: retries });

        const retryPrompt = `
Your previous tool call was invalid:
${JSON.stringify(toolCall)}

Error: ${error}

Please fix the tool call. Output ONLY valid JSON.
`;

        const retryRaw = await streamLLM(this.llmUrl, retryPrompt);
        const retryParsed = this.parseTool(retryRaw);

        if (retryParsed) {
          const validation = this.validateToolCall(retryParsed);
          if (validation.valid) {
            Object.assign(toolCall, retryParsed);
            valid = true;
          } else {
            error = validation.error;
          }
        } else {
          error = 'Could not parse JSON from your response.';
        }
      }

      if (!valid) {
        throw new Error(`Invalid tool call generated by LLM after retries: ${error}`);
      }

      // EXECUTE TOOL
      const result = await this.mcp.call(toolCall.tool, toolCall.args);
      this.audit.log(step, 'tool_result', result);

      // APPEND TO HISTORY
      history += `
Assistant (tool call): ${JSON.stringify(toolCall)}
Tool result: ${JSON.stringify(result.result)}
`;

      step++;
    }

    return 'Maximum steps reached.';
  }
}
